-- ***** AREA DE USUARIOS Y PAGINAS
CREATE TABLE USERS(
	USERNAME VARCHAR PRIMARY KEY,
	PASS VARCHAR
);
	
CREATE TABLE ROLES (
	CODE INTEGER PRIMARY KEY,
	DESCRIPTION VARCHAR
);

CREATE TABLE ROLESBYUSER (
	USERNAME VARCHAR REFERENCES USERS(USERNAME), 
	ROLECODE INTEGER REFERENCES ROLES(ID),
	PRIMARY KEY (USERNAME, ROLECODE)
);

-- ***** AREA DE EVENTOS Y PROMOTORES
CREATE TABLE PROMOTERS(
	CODE INTEGER PRIMARY KEY, 
	NAME VARCHAR, 
	ADDRESS VARCHAR, 
	TELEPHONE VARCHAR, 
	ACCOUNT VARCHAR, 
	BANK VARCHAR, 
	COMISSION INTEGER,
	USERNAME VARCHAR REFERENCES USERS(USERNAME)
);

CREATE TABLE EVENTTYPES (
	CODE INTEGER PRIMARY KEY,
	DESCRIPTION VARCHAR
);

CREATE TABLE EVENTS (
	CODE INTEGER PRIMARY KEY, 
	NAME VARCHAR, 
	EVENTTYPECODE INTEGER REFERENCES EVENTTYPES(CODE), 
	ARTISTS VARCHAR, 
	DATE VARCHAR, 
	PLACE VARCHAR,
	PROMOTERID INTEGER REFERENCES PROMOTERS(CODE)
);

-- ***** AREA DE ENTRADAS
CREATE TABLE LOCATIONTYPES(
	CODE INTEGER PRIMARY KEY,
	DESCRIPTION VARCHAR
);

CREATE TABLE LOCATIONS(
	LOCATIONTYPEID INTEGER REFERENCES LOCATIONTYPES(CODE),
	EVENTID INTEGER REFERENCES EVENT(CODE),
	PRICE INTEGER,
	QUANTITY INTEGER,
	NUMBERED INTEGER, --BOOLEAN
	PRIMARY KEY(LOCATIONTYPEID, EVENTID)
);
	
CREATE TABLE CUSTOMERS
(
	ID VARCHAR PRIMARY KEY,
	NAME VARCHAR,
	ADDRESS VARCHAR,
	TELEPHONE VARCHAR,
	CARDNUMBER VARCHAR,
	CARDTYPE VARCHAR
);

CREATE TABLE TICKETS(
	CODE INTEGER PRIMARY KEY,
	LOCATIONTYPEID INTEGER,
	EVENTID INTEGER,
	CUSTOMERID VARCHAR REFERENCES CUSTOMERS(ID),
	DATE VARCHAR,
	QUANTITY INTEGER, 
	AMOUNT INTEGER,
	FOREIGN KEY(LOCATIONTYPEID, EVENTID) REFERENCES LOCATIONS(LOCATIONTYPEID, EVENTID)
);

CREATE TABLE NUMBEREDLOCATION(
	LOCATIONNUMBER INTEGER,
	--LOCATIONTYPE INTEGER,
	--EVENTID INTEGER,
	TICKETID INTEGER REFERENCES TICKETS(CODE),
	--FOREIGN KEY(LOCATIONTYPE, EVENTID) REFERENCES LOCATIONS(LOCATIONTYPEID, EVENTID)
	PRIMARY KEY(LOCATIONNUMBER, TICKETID);
);


INSERT INTO ROLES VALUES(1, 'Administrator');
INSERT INTO ROLES VALUES(2, 'Promoter');
insert into users values('admin', 'pass');
insert into rolesbyuser values('admin', 1);

INSERT INTO EVENTTYPES VALUES(1, 'Concierto');
INSERT INTO EVENTTYPES VALUES(2, 'Recital');
INSERT INTO EVENTTYPES VALUES(3, 'Obra de Teatro');

INSERT INTO LOCATIONTYPES VALUES(1, 'Sol');
INSERT INTO LOCATIONTYPES VALUES(2, 'Sombra');
INSERT INTO LOCATIONTYPES VALUES(3, 'Platea');
INSERT INTO LOCATIONTYPES VALUES(4, 'Palco');
INSERT INTO LOCATIONTYPES VALUES(5, 'Preferencial');
INSERT INTO LOCATIONTYPES VALUES(6, 'VIP');